// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: handbag.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Research.ProtoBuf {

  /// <summary>Holder for reflection information generated from handbag.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class HandbagReflection {

    #region Descriptor
    /// <summary>File descriptor for handbag.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HandbagReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1oYW5kYmFnLnByb3RvEhFSZXNlYXJjaC5Qcm90b0J1ZhoSYWRkcmVzc19i",
            "b29rLnByb3RvGgx3YWxsZXQucHJvdG8iTwoHSGFuZGJhZxIaCgRib29rGAEg",
            "ASgLMgwuQWRkcmVzc0Jvb2sSKAoFcHVyc2UYAiABKAsyGS5SZXNlYXJjaC5Q",
            "cm90b0J1Zi5XYWxsZXRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Research.ProtoBuf.AddressBookReflection.Descriptor, global::Research.ProtoBuf.WalletReflection.Descriptor, },
          new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
            new pbr::GeneratedCodeInfo(typeof(global::Research.ProtoBuf.Handbag), global::Research.ProtoBuf.Handbag.Parser, new[]{ "Book", "Purse" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Handbag : pb::IMessage<Handbag> {
    private static readonly pb::MessageParser<Handbag> _parser = new pb::MessageParser<Handbag>(() => new Handbag());
    public static pb::MessageParser<Handbag> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Research.ProtoBuf.HandbagReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Handbag() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Handbag(Handbag other) : this() {
      Book = other.book_ != null ? other.Book.Clone() : null;
      Purse = other.purse_ != null ? other.Purse.Clone() : null;
    }

    public Handbag Clone() {
      return new Handbag(this);
    }

    /// <summary>Field number for the "book" field.</summary>
    public const int BookFieldNumber = 1;
    private global::Research.ProtoBuf.AddressBook book_;
    public global::Research.ProtoBuf.AddressBook Book {
      get { return book_; }
      set {
        book_ = value;
      }
    }

    /// <summary>Field number for the "purse" field.</summary>
    public const int PurseFieldNumber = 2;
    private global::Research.ProtoBuf.Wallet purse_;
    public global::Research.ProtoBuf.Wallet Purse {
      get { return purse_; }
      set {
        purse_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Handbag);
    }

    public bool Equals(Handbag other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Book, other.Book)) return false;
      if (!object.Equals(Purse, other.Purse)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (book_ != null) hash ^= Book.GetHashCode();
      if (purse_ != null) hash ^= Purse.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (book_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Book);
      }
      if (purse_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Purse);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (book_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Book);
      }
      if (purse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Purse);
      }
      return size;
    }

    public void MergeFrom(Handbag other) {
      if (other == null) {
        return;
      }
      if (other.book_ != null) {
        if (book_ == null) {
          book_ = new global::Research.ProtoBuf.AddressBook();
        }
        Book.MergeFrom(other.Book);
      }
      if (other.purse_ != null) {
        if (purse_ == null) {
          purse_ = new global::Research.ProtoBuf.Wallet();
        }
        Purse.MergeFrom(other.Purse);
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (book_ == null) {
              book_ = new global::Research.ProtoBuf.AddressBook();
            }
            input.ReadMessage(book_);
            break;
          }
          case 18: {
            if (purse_ == null) {
              purse_ = new global::Research.ProtoBuf.Wallet();
            }
            input.ReadMessage(purse_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
